# ===========================
# Server Configuration
# ===========================
server.port=8080

# ===========================
# MongoDB Configuration
# ===========================
spring.data.mongodb.uri=mongodb://localhost:27017/quanlykhachsan

# ===========================
# Application Configuration
# ===========================
spring.application.name=QuanLyKhachSan
